### ISSUE TITLE
Not detecting GPU even with OpenCL working.

### ISSUE THREAD

**Issue by NarwhalOS** [tmpim/kristforge#11]
I managed to install OpenCL on my ATI Radeon 2400 XT, Before it gave me a OpenCL error now that's fixed. But it doesn't detect my GPU

**Comment by dmarcuse** [comment]
Could you share the output of `kristforge info` and `clinfo`? You can download clinfo for windows [here](https://github.com/Oblomov/clinfo#windows-support) or install it from your distro's package manager on linux.

**Comment by NarwhalOS** [comment]
clinfo: Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 18.0.5
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Clover
  clCreateContext(NULL, ...) [default]            No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.8
  ICD loader Profile                              OpenCL 1.2
	NOTE:	your OpenCL library declares to support OpenCL 1.2"
kristforge: CPU:
	Threads: 2
	Supported kernels: unoptimized
	Unsupported kernels: SHA
Also I'm on Ubuntu

**Comment by dmarcuse** [comment]
You have an OpenCL driver installed, but that driver isn't providing any devices (note `Number of devices 0`). Usually this means you installed the wrong driver for your hardware, or your hardware simply doesn't support OpenCL.

I can't find much about OpenCL support for your card, but given that it's a pretty old one, I'd guess that it's simply not supported. AMD maintains a proprietary driver stack including an OpenCL driver - AMDGPU-PRO - but it's relatively new as well, so I'm not sure it would support your card either. Unfortunately, you might just be out of luck here.
