### ISSUE TITLE
Kristforge panics when Intel iGPU OpenCL runtime installed

### ISSUE THREAD

**Issue by ghost** [tmpim/kristforge#18]
I am trying to use my CPU and iGPU on my Arch Linux laptop to mine Krist and while my CPU works fine when I have `intel-compute-runtime` uninstalled but when I install that package to get iGPU OpenCL mining working, Kristforge now panics instead of mining.

```thread 'main' panicked at 'Kernel argument type mismatch - OpenCL type "char*" is not compatible with Buffer<HostWriteOnly, u8> for argument #0 (KernelArgInfo { CL_KERNEL_ARG_ADDRESS_QUALIFIER: Constant, CL_KERNEL_ARG_ACCESS_QUALIFIER: None, CL_KERNEL_ARG_TYPE_NAME: "char*", CL_KERNEL_ARG_TYPE_QUALIFIER: ArgTypeQualifier(0b0 = NONE), CL_KERNEL_ARG_NAME: "input" }) of kernel UnboundKernel { CL_KERNEL_FUNCTION_NAME: "mine", CL_KERNEL_NUM_ARGS: 4, CL_KERNEL_REFERENCE_COUNT: 1, CL_KERNEL_CONTEXT: 0x5566489b96b0, CL_KERNEL_PROGRAM: 0x556648ba9930, CL_KERNEL_ATTRIBUTES: "" }', /cargo/registry/src/github.com-1ecc6299db9ec823/dynamic_ocl-0.1.0-alpha.1/src/safe/kernel/types.rs:218:25```

**Comment by dmarcuse** [comment]
I just published a [release including a fix for this](https://github.com/tmpim/kristforge/releases/tag/v3.1.6), please let me know if there's still issues.

**Comment by ghost** [comment]
Yep, this fixed the issue! Kristforge successfully initialised my iGPU!

![Screenshot_2022-02-20_07-58-52](https://user-images.githubusercontent.com/98581137/154833822-e6e3ba0b-edb1-4549-a7a6-4eb00ca43c7f.png)
