### ISSUE TITLE
No GPU usage.

### ISSUE THREAD

**Issue by 0x-Stealth** [tmpim/kristforge#19]
I flag it to use no CPU. It still uses 8% CPU and doesn't use GPU. I tell it ot use both, only uses CPU.

**Comment by dmarcuse** [comment]
Can you show the output of `kristforge info` and the command you're using to start the miner?

**Comment by 0x-Stealth** [comment]
kristforge info
"OpenCL device "NVIDIA GeForce RTX 3080":
        Compute units: 68
        Clock frequency: 1755
CPU:
        Threads: 16
        Supported kernels: unoptimized
        Unsupported kernels: SHA
"

I use kristforge mine ki2mwm5bpf

**Comment by dmarcuse** [comment]
Can you provide a screenshot of the output of the `kristforge mine` command, and a copy of the log file? (The log file is probably at `~/.local/share/kristforge/kristforge.log` for Linux systems, and `%appdata%\kristforge\kristforge.log` for Windows)

**Comment by 0x-Stealth** [comment]
![image](https://user-images.githubusercontent.com/42773083/160699921-0b864a66-7195-420b-a687-b14d81eb501d.png)
[kristforge.log](https://github.com/tmpim/kristforge/files/8374756/kristforge.log)

**Comment by dmarcuse** [comment]
I don't see the problem, it's using both the GPU and the CPU. What's the issue?

**Comment by 0x-Stealth** [comment]
It says its using GPU, but really it isn't. In taskmanager its using 0 CPU, I messed with settings and got it to 60gh/s, but was it really 60gh/s? No, because that's wayt too high and it would use 100% gpu not 0

**Comment by Lemmmy** [comment]
5.6 Gh/s sounds right for a 3080 on Windows

**Comment by dmarcuse** [comment]
There's nothing obvious in the logs that indicates an issue. What settings are getting you 60 GH/s? And when running for a few minutes, are there any blocks submitted?

**Comment by dmarcuse** [comment]
Any update on this @Stealthr?

**Comment by xAnavrins** [comment]
GPU mining uses CUDA cores, you have to look at CUDA stats to see the effects of mining, otherwise taskmgr shows 3D stats by default.
![image](https://user-images.githubusercontent.com/5376823/163295469-af09fb4f-08a3-4aa3-82eb-a402ce5c9f94.png)

A 3090 gets 7.3 Gh/s, there's no way you're getting 60 with your 3080, your setup is working exactly as expected
