### ISSUE TITLE
JSON Mining Error

### ISSUE THREAD

**Issue by Apethesis** [tmpim/kristforge#20]
So recently when i have been trying to mine krist i have been getting this error
`Mining error: JsonError(Error("EOF while parsing a value", line: 1, column: 0))`
I'm guessing this is cause of the move to krist.dev? Not sure.

**Comment by 1lann** [comment]
Mining is no longer permitted on Krist. (as it says "Block submission is now disabled" on https://krist.dev/)

**Comment by dmarcuse** [comment]
On that note, I think I'm going to archive this repository.
