### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by AutumnalModding** [tmpim/kristforge#8]
With a fresh install of the Visual Studio Build Tools and the Rust toolchain-whatever, running `cargo build --verbose` fails.
Output: https://pastebin.com/eZ1X5Qu0

**Comment by dmarcuse** [comment]
The rust version of this project isn't yet functional, but that error seems to indicate that you don't have an OpenCL driver installed. Find and install the appropriate drivers for your GPU or CPU, and that should include an OpenCL driver.
