### ISSUE TITLE
Massive Temporary Files

### ISSUE THREAD

**Issue by AlanCretel** [tmpim/kristforge#9]
Hi, when using this miner, a lot of temporary files are saved and takes a lot of place like 2Go in at least 10 minutes of use.

**Comment by Lemmmy** [comment]
Which files? What are they called, and where are they stored?

**Comment by dmarcuse** [comment]
Can you give more details? What temporary files and where, what OS and hardware... Kristforge doesn't directly write any files except for a log file (which absolutely should not take up 2 GB), but your system's OpenCL driver could conceivably be generating some junk.

**Comment by AlanCretel** [comment]
I'm using a laptop with Win 10, I have an Intel I3-4005U with an NVIDIA GeForce 920M and Intel HD Graphics 4400 and 4G RAM. Temp files are saved at C:\Windows\TEMP\.
File names starts by "Application_92771390" or "AppxErrorReport_92771390" with ".evtx" extension.

I seen this error when my hard disk were filled up with this files x') (That's not my main computer ^^)

Thanks for your help.

**Comment by 1lann** [comment]
With a quick Google search, it appears to be related to UWP apps. kristforge is not a UWP app, is there a reason you think these files are associated with kristforge? Try following these steps as well: https://support.microsoft.com/en-us/help/4458149/windows-10-low-disk-space-error-due-to-a-full-temp-folder
